In [1]:
import pandas as pd

In [5]:
#Leo el archivo Excel
df = pd.read_excel('../data/raw/poblacion_dane_2018_2042.xlsx')

#Muestro las primeras 5 filas del DataFrame
print(df.head())

                                          Unnamed: 0 Unnamed: 1
0                                                NaN        NaN
1                                                NaN        NaN
2  PROYECCIONES DE POBLACIÓN Y ESTUDIOS DEMOGRÁFI...        NaN
3                                                NaN        NaN
4     DIRECCIÓN TÉCNICA DE CENSOS Y DEMOGRAFÍA (DCD)        NaN

In [6]:
#Leer primeras 20 filas para inspeccionar el contenido
muestra = pd.read_excel('../data/raw/poblacion_dane_2018_2042.xlsx', header=None, nrows=20)
muestra

,0,1
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,PROYECCIONES DE POBLACIÓN Y ESTUDIOS DEMOGRÁFI...,NaN
4,NaN,NaN
5,DIRECCIÓN TÉCNICA DE CENSOS Y DEMOGRAFÍA (DCD),NaN
6,NaN,NaN
7,NaN,NaN
8,1.,Introducción PPED
9,NaN,Actualización de la serie municipal de poblaci...
10,2.,Desagregación por área geográfica
11,NaN,MUNICIPAL. PROYECCIONES DE POBLACIÓN POR ÁREA ...

In [7]:
poblacion = pd.read_excel(
    '../data/raw/poblacion_dane_2018_2042.xlsx',
    sheet_name='PobMunicipalxÁrea',
    header=7,
    dtype={'DP': str, 'MPIO': str},
)
poblacion.shape

(84234, 7)

In [10]:
poblacion.tail(12)

,DP,DPNOM,MPIO,DPMP,AÑO,ÁREA GEOGRÁFICA,TOTAL
84222,99,Vichada,99624,Santa Rosalía,2042.0,Total,3716.0
84223,99,Vichada,99773,Cumaribo,2042.0,Cabecera Municipal,4461.0
84224,99,Vichada,99773,Cumaribo,2042.0,Centros Poblados y Rural Disperso,176148.0
84225,99,Vichada,99773,Cumaribo,2042.0,Total,180609.0
84226,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84227,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84228,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84229,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84230,"Fuente: DANE, Proyecciones de población - Dire...",NaN,NaN,NaN,NaN,NaN,NaN
84231,Nota: Desde el 1 de diciembre de 2019 comenzó ...,NaN,NaN,NaN,NaN,NaN,NaN
84232,Nota: A partir del decreto 0284 del 26 de dic...,NaN,NaN,NaN,NaN,NaN,NaN
84233,Actualizado el 30 de Julio de 2025,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
poblacion = poblacion.dropna(subset=['MPIO'])
poblacion.shape

(84225, 7)

In [12]:
poblacion['ÁREA GEOGRÁFICA'].value_counts()

ÁREA GEOGRÁFICA
Cabecera Municipal                   28075
Centros Poblados y Rural Disperso    28075
Total                                28075
Name: count, dtype: int64

In [13]:
total = poblacion[poblacion['ÁREA GEOGRÁFICA'] == 'Total']
total.shape

(28075, 7)

In [16]:
total[total['AÑO'] == 2025]['TOTAL'].sum()

np.float64(53057212.0)